from fpdf import FPDF

class PDF(FPDF):
    def header(self):
     if self.page_no() > 1:
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(99, 102, 241)
        self.cell(0, 10, 'Fake Engagement Detection System - Model Explanation', align='C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()}', align='C')

pdf = PDF()
pdf.set_auto_page_break(auto=True, margin=15)
pdf.add_page()

def section_title(pdf, title):
    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 10, title, ln=True)
    pdf.set_draw_color(99, 102, 241)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

def body(pdf, text):
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(30, 41, 59)
    pdf.multi_cell(0, 6, text)
    pdf.ln(3)

def bold_line(pdf, label, value):
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(50, 6, label, ln=False)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 6, value, ln=True)

# Title
pdf.set_font('Helvetica', 'B', 18)
pdf.set_text_color(99, 102, 241)
pdf.cell(0, 12, 'Fake Engagement Detection System', ln=True, align='C')
pdf.set_font('Helvetica', '', 11)
pdf.set_text_color(100, 100, 100)
pdf.cell(0, 8, 'Behavioural Analytics Hackathon - Problem Statement 3', ln=True, align='C')
pdf.cell(0, 8, 'Author: Thiruchelvan P J', ln=True, align='C')
pdf.ln(5)

# Section 1
section_title(pdf, '1. Problem Understanding')
body(pdf, 'Social media platforms face a growing challenge of fake engagement generated by bots and coordinated inauthentic accounts. This fake activity distorts genuine behavioural patterns, misleads advertisers, and manipulates content algorithms.')
body(pdf, 'The goal of this project is to build a behavioural analytics system that differentiates organic users from bots, assigns an Authenticity Score (0-100) to each account, identifies key behavioural triggers behind the prediction, and provides a visual dashboard for analysis.')

# Section 2
section_title(pdf, '2. Dataset Description & Assumptions')
bold_line(pdf, 'Dataset Type:', 'Synthetic')
bold_line(pdf, 'Total Records:', '1000 users (300 bots, 700 organic)')
bold_line(pdf, 'Reason:', 'No real labeled dataset available with required behavioural features')
pdf.ln(2)
body(pdf, 'How it was generated: Bot accounts were simulated with high posting frequency, regular timing, short comments, and high night activity - patterns consistent with automated behaviour research. Organic accounts were simulated with irregular posting times, longer comments, varied language, and normal activity hours. NumPy random distributions were used with a fixed seed (42) for reproducibility.')
body(pdf, 'Key Assumptions:\n- Bots post 50-200 times per day vs humans 1-10 times\n- Bots have very regular posting times (low std deviation)\n- Bots use repetitive language (low unique words ratio)\n- Bots are more active at night (0.6-1.0 night activity ratio)\n- Organic users have older, more complete accounts')

# Section 3
section_title(pdf, '3. Feature Engineering')
features = [
    ('avg_posts_per_day', 'Bots post significantly more than humans'),
    ('posting_time_std', 'Bots post at very regular intervals'),
    ('engagement_burst_score', 'Bots create sudden spikes in engagement'),
    ('followers_following_ratio', 'Bots follow many but have few followers'),
    ('avg_comment_length', 'Bot comments are short and repetitive'),
    ('unique_words_ratio', 'Bots reuse the same phrases repeatedly'),
    ('account_age_days', 'Bot accounts are typically newer'),
    ('profile_completeness', 'Bots have incomplete profiles'),
    ('night_activity_ratio', 'Bots are active at unusual hours'),
]
for feat, insight in features:
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(70, 6, feat, ln=False)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 6, insight, ln=True)
pdf.ln(3)

# Section 4
section_title(pdf, '4. Model Selection & Reasoning')
bold_line(pdf, 'Algorithm:', 'Random Forest Classifier')
pdf.ln(2)
body(pdf, 'Why Random Forest?\n- Handles non-linear relationships between behavioural features well\n- Provides feature importance scores for explainability\n- Robust to outliers in behavioural data\n- Works well with mixed feature types\n- Easy to interpret for stakeholders')
body(pdf, 'Hyperparameters: n_estimators=100, max_depth=10, random_state=42\nTrain/Test Split: 80% training, 20% testing with stratification')

# Section 5
section_title(pdf, '5. Evaluation Metrics')
body(pdf, 'Precision: 1.00 | Recall: 1.00 | F1-Score: 1.00 | ROC-AUC: 1.00 | Accuracy: 100%')
body(pdf, 'Note: Perfect scores are expected because the synthetic dataset was generated with clearly separated behavioural distributions. In a real-world scenario with noisy data, scores would typically range between 0.85-0.95.')

# Section 6
section_title(pdf, '6. Behavioural Insights Derived')
insights = [
    ('1. engagement_burst_score', 'Most powerful indicator. Bots create sudden unnatural spikes in engagement.'),
    ('2. night_activity_ratio', 'Bots operate around the clock without human sleep patterns.'),
    ('3. avg_posts_per_day', 'Volume of posts is 10-20x higher for bots than organic users.'),
    ('4. unique_words_ratio', 'Bots reuse templated language resulting in very low linguistic diversity.'),
    ('5. account_age_days', 'Newly created accounts are far more likely to be bots.'),
]
for label, desc in insights:
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 6, label, ln=True)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 6, desc, ln=True)
    pdf.ln(1)

# Section 7
section_title(pdf, '7. System Output')
body(pdf, 'Each user account receives:\n- Authenticity Score (0-100): Higher = more likely organic\n- Bot Probability (0-1): Confidence of being a bot\n- Risk Label: Bot / Suspicious / Organic\n- Visual Dashboard: Interactive Plotly Dash interface')

# Save
pdf.output('model_explanation.pdf')
print('✓ PDF created: docs/model_explanation.pdf')
